#!/bin/bash
STARTUP_LOG_FILE=/var/log/startup.log
STARTUP_APPS=(sshd__START_SCRIPT_SMB_APPS__ nginx php-fpm php56-fpm redis-server memcached mysqld)
STARTUP_APP_ARGS=('-D'__START_SCRIPT_SMB_CONFS__ '-c /etc/nginx/nginx.conf' '-c /etc/php/php.ini' '-c /etc/php56/php.ini' '/etc/redis.conf' '-l 127.0.0.1 -o modern -u root' '-u root')
DEFAULT_PWD='123qwe!'
WEB_DIR_ROOT_PATH='/data/vhosts/'
USR_BIN='/usr/bin/'
DEFAULT_INDEX_FILE=$(cat <<EOF
<?php
if ('phpinfo' == \$_GET['a'])
{
    phpinfo();
    die;
}
echo "<h1>欢迎使用</h1>运行在Docker上的LNMP环境。查看<a href='?a=phpinfo'>phpinfo</a>。<br/>build by <a href='https://github.com/viger/docker'>viger</a>.";
EOF
)

make_dir() {
    [ ! -d "$1" ] && mkdir -p $1 && record_log "make directory $1 successed."
}

set_user() {
    [ -d "$1" ] && chown starcor:users -R $1
}

init_mysql_db() {
    [ ! -d "/data/mysql" ] \
    && mkdir -p /data/mysql \
    && ${USR_BIN}mysql_install_db --user=mysql --basedir=/usr/ --datadir=/data/mysql \
    && [ -x "${USR_BIN}mysqladmin" ] && ${USR_BIN}mysqladmin -u root password '$DEFAULT_PWD' \
    && record_log "install database successed."
}

record_log() {
    echo "[$(date +"%Y-%m-%d %T")] $1" >> $STARTUP_LOG_FILE
}

init_web_dir() {
    local dir_name=$1
    [ -z "$1" ] && record_log "web name is null." && return

    make_dir ${WEB_DIR_ROOT_PATH}$1/logs && make_dir ${WEB_DIR_ROOT_PATH}$1/public
    echo 1
}

startup_app() {
    local idx=0
    local app_bin=""
    for app in "${STARTUP_APPS[@]}"; do
        app_bin=${USR_BIN}$app
        if [ ! -z "$app_bin" ] && [ -x "$app_bin" ] && [ -z "$(ps aux | grep "$app" | grep -v grep)" ]; then
            $app_bin ${STARTUP_APP_ARGS[${idx}]} &
            record_log "startup $app_bin ${STARTUP_APP_ARGS[${idx}]}";
        fi
        idx=$(expr $idx + 1);
    done
}

sleep 3

init_web_dir default && echo -e $DEFAULT_INDEX_FILE > ${WEB_DIR_ROOT_PATH}default/public/index.php
init_web_dir bugfix_devp && make_dir "${WEB_DIR_ROOT_PATH}svn_branches/"

startup_app

set_user /data/vhosts

make_dir /var/log/php/

tail -f $STARTUP_LOG_FILE